### ISSUE TITLE
pyarrow.lib.ArrowInvalid: column 1 named title expected length 0 but got length 350

### ISSUE THREAD

**Issue by Shenrui-Ma** [nbalepur/expository-text-generation#1]
This is what happened after running scrape_web.py
<img width="982" alt="92779a23a913ebc5c2a3b472385d6c7" src="https://github.com/user-attachments/assets/42c605c3-f0a0-4c45-bf41-3fefa5b07f38">
Took me 5 hours to get nothing.It didn't even save anything for backup.

**Comment by nbalepur** [comment]
Thanks for raising an issue, and sorry for the trouble! The web scraping code could be outdated if Google changed anything. I'll take a look today!

And if that doesn't work, if you give me your email I can send you the dataset

**Comment by nbalepur** [comment]
I just pushed a change for the data collection code, do let me know if you have more issues!

**Comment by Shenrui-Ma** [comment]
My Gmail address is shenruima@gmail.com.We only need the Wiki_cs dataset. Really appreciated!
